'use client';
import {useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Plan={id:string;guild_id:number;name:string;description:string;kind:string;required_invites:number;ram_mb:number;cpu_percent:number;disk_mb:number;image?:string|null;egg_id?:number|null;docker_image?:string|null;enabled:boolean;sort_order:number;config:Record<string,unknown>};
type Node={id:string;name:string;kind:string;endpoint:string;enabled:boolean;maintenance:boolean;capacity:Record<string,unknown>};
type Server={id:string;name:string;kind:string;status:string;provider_id?:string|null};
const blank:Omit<Plan,'id'>={guild_id:0,name:'',description:'',kind:'vps',required_invites:1,ram_mb:4096,cpu_percent:200,disk_mb:20480,image:'ubuntu:24.04',egg_id:null,docker_image:'ubuntu:24.04',enabled:true,sort_order:0,config:{}};
export default function Home(){
 const [token,setToken]=useState(''),[input,setInput]=useState(''),[tab,setTab]=useState('Overview'),[data,setData]=useState<any>({}),[plans,setPlans]=useState<Plan[]>([]),[nodes,setNodes]=useState<Node[]>([]),[servers,setServers]=useState<Server[]>([]),[audit,setAudit]=useState<any[]>([]),[form,setForm]=useState<any>(blank),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 async function api(path:string,init:RequestInit={}){const r=await fetch(API+path,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(init.headers||{})}});if(!r.ok)throw Error((await r.json().catch(()=>({detail:r.statusText}))).detail||r.statusText);return r.json()}
 async function refresh(){if(!token)return;setLoading(true);try{const [o,p,n,s,a]=await Promise.all([api('/api/v1/dashboard/overview'),api('/api/v1/dashboard/plans'),api('/api/v1/dashboard/nodes'),api('/api/v1/dashboard/servers'),api('/api/v1/dashboard/audit?limit=100')]);setData(o);setPlans(p);setNodes(n);setServers(s);setAudit(a)}catch(e:any){setError(e.message);setToken('');sessionStorage.removeItem('arvex_admin_token')}finally{setLoading(false)}}
 useEffect(()=>{const t=sessionStorage.getItem('arvex_admin_token');if(t)setToken(t)},[]);useEffect(()=>{refresh()},[token]);
 async function save(){try{await api(editing?`/api/v1/dashboard/plans/${editing}`:'/api/v1/dashboard/plans',{method:editing?'PATCH':'POST',body:JSON.stringify(form)});setEditing(null);setForm(blank);refresh()}catch(e:any){setError(e.message)}}
 async function move(id:string,direction:'up'|'down'){try{await api(`/api/v1/dashboard/plans/${id}/move`,{method:'POST',body:JSON.stringify({direction})});refresh()}catch(e:any){setError(e.message)}}
 async function disable(id:string){if(!confirm('Disable this plan?'))return;try{await api(`/api/v1/dashboard/plans/${id}`,{method:'DELETE'});refresh()}catch(e:any){setError(e.message)}}
 async function maintenance(id:string,value:boolean){try{await api(`/api/v1/dashboard/nodes/${id}/maintenance`,{method:'POST',body:JSON.stringify({maintenance:value})});refresh()}catch(e:any){setError(e.message)}}
 if(!token)return <main className="login"><div className="loginCard"><div className="brand">ARVEX<span>CONTROL</span></div><p className="eyebrow">SECURE ADMIN ACCESS</p><h1>Control Center</h1><p>Server-side dashboard token required.</p><input type="password" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&setToken(input)} placeholder="Admin dashboard token"/><button onClick={()=>{setToken(input);sessionStorage.setItem('arvex_admin_token',input)}}>Unlock Dashboard</button>{error&&<div className="alert">{error}</div>}</div></main>;
 const tabs=['Overview','Invite Plans','Nodes','Servers','Deployments','Users','Audit Logs'];
 return <main className="shell"><aside><div className="brand">ARVEX<span>CONTROL</span></div><nav>{tabs.map(x=><a key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</a>)}</nav><button className="logout" onClick={()=>{setToken('');sessionStorage.removeItem('arvex_admin_token')}}>Lock</button></aside><section className="content"><header><div><p className="eyebrow">HOSTING AUTOMATION SAAS</p><h1>{tab}</h1></div><div className="status">● {loading?'Syncing':'Protected'}</div></header>{error&&<div className="alert">{error}</div>}
 {tab==='Overview'&&<><div className="grid">{[['Users',data.users],['Servers',data.servers],['Active Plans',data.plans],['Nodes',data.nodes],['Active Deployments',data.active_deployments],['Failed Deployments',data.failed_deployments]].map(x=><div className="card" key={x[0] as string}><small>{x[0]}</small><strong>{x[1]??0}</strong><span>Live metric</span></div>)}</div><div className="panel"><h2>Provisioning pipeline</h2><p>Discord signed request → authorization → PostgreSQL transaction → deployment queue → isolated provider → private delivery.</p><div className="pipeline"><i>Discord</i><b>→</b><i>HMAC</i><b>→</b><i>Queue</i><b>→</b><i>Docker / Pterodactyl</i><b>→</b><i>DM</i></div></div></>}
 {tab==='Invite Plans'&&<><div className="panel"><div className="toolbar"><h2>{editing?'Edit plan':'Create plan'}</h2><button onClick={()=>{setEditing(null);setForm(blank)}}>New Plan</button></div><div className="formgrid">{[['guild_id','Guild ID','number'],['name','Name','text'],['required_invites','Invites','number'],['ram_mb','RAM MB','number'],['cpu_percent','CPU %','number'],['disk_mb','Disk MB','number'],['image','Image','text'],['docker_image','Docker image','text'],['egg_id','Egg ID','number'],['sort_order','Order','number']].map(([k,l,t])=><label key={k}>{l}<input type={t} value={form[k]??''} onChange={e=>setForm({...form,[k]:t==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value})}/></label>)}<label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Kind<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="vps">Docker VPS</option><option value="game">Pterodactyl Game</option></select></label></div><div className="actions"><button onClick={save}>{editing?'Save Changes':'Create Plan'}</button>{editing&&<button className="secondary" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</div></div><div className="panel"><h2>Configured plans</h2>{plans.map((p,i)=><div className="planrow" key={p.id}><div><b>{p.name}</b><span>{p.required_invites} invites · {Math.round(p.ram_mb/1024)}GB · {Math.max(1,Math.round(p.cpu_percent/100))} vCPU · {Math.round(p.disk_mb/1024)}GB · {p.kind}</span></div><div className="rowbuttons"><button disabled={i===0} onClick={()=>move(p.id,'up')}>↑</button><button disabled={i===plans.length-1} onClick={()=>move(p.id,'down')}>↓</button><button onClick={()=>{setEditing(p.id);setForm({...p})}}>Edit</button><button className="danger" onClick={()=>disable(p.id)}>Disable</button></div></div>)}</div></>}
 {tab==='Nodes'&&<div className="panel"><h2>Infrastructure nodes</h2>{nodes.map(n=><div className="planrow" key={n.id}><div><b>{n.name}</b><span>{n.kind} · {n.endpoint} · {n.maintenance?'MAINTENANCE':'AVAILABLE'}</span></div><div className="rowbuttons"><button onClick={()=>maintenance(n.id,!n.maintenance)}>{n.maintenance?'Enable':'Maintenance'}</button></div></div>)}</div>}
 {tab==='Servers'&&<div className="panel"><h2>All customer servers</h2>{servers.map(s=><div className="planrow" key={s.id}><div><b>{s.name}</b><span>{s.kind} · {s.status} · {s.provider_id||'pending'}</span></div></div>)}</div>}
 {tab==='Deployments'&&<div className="panel"><h2>Deployment queue</h2>{data.active_deployments===0?<p>No active deployments.</p>:<p>{data.active_deployments} jobs currently queued or provisioning. Use the API deployment view for detailed job records.</p>}</div>}
 {tab==='Users'&&<div className="panel"><h2>Customer accounts</h2><p>User records are intentionally served without secrets. Use the protected dashboard users endpoint for management tooling.</p></div>}
 {tab==='Audit Logs'&&<div className="panel"><h2>Security & audit events</h2>{audit.map(x=><div className="audit" key={x.id}><b>{x.action}</b><span>{x.target}</span><small>{new Date(x.created_at).toLocaleString()}</small></div>)}</div>}
 </section></main>
}
